[build]
  publish = "."

[[redirects]]
  from = "/ios"
  to = "/ios.html"
  status = 200

[[redirects]]
  from = "/android"
  to = "/android.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 