[build]
  publish = "."

[[headers]]
  for = "/.well-known/apple-app-site-association"
  [headers.values]
    Content-Type = "application/json"
    Cache-Control = "public, max-age=300"

[[redirects]]
  from = "/__/auth/action"
  to = "/__/auth/action/index.html"
  status = 200

[[redirects]]
  from = "/ios"
  to = "/ios.html"
  status = 200

[[redirects]]
  from = "/android"
  to = "/android.html"
  status = 200

[[redirects]]
  from = "/terms"
  to = "/terms.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 